/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LabSemana6;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.Random;
import javax.swing.*;
import java.awt.event.*;

import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
/**
 *
 * @author adrianaguilar
 */
public class Aguilar_Adrian_Main extends javax.swing.JFrame {
    
    
    Random random = new Random();
    String[] palabrasiniciales = {"CARRO", "ERICK", "LAPTOP", "AHORCADO", "HONDURAS", "PROGRAMACION", "CELULAR", "CODIGO"};
    char[] palabraActual;
    char[] palabraOculta;
    int oportunidades;

    /**
     * Creates new form Aguilar_Adrian_Main
     */
    public Aguilar_Adrian_Main() {
        initComponents();
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cambiarPalabras = new javax.swing.JButton();
        iniciarJUEGO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Apple Braille", 0, 24)); // NOI18N
        jLabel1.setText("JUEGO ADIVINAR PALABRA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        cambiarPalabras.setBackground(new java.awt.Color(204, 255, 204));
        cambiarPalabras.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cambiarPalabras.setText("CAMBIAR PALABRAS");
        jPanel1.add(cambiarPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 220, 40));

        iniciarJUEGO.setBackground(new java.awt.Color(204, 255, 204));
        iniciarJUEGO.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        iniciarJUEGO.setText("INICIAR JUEGO");
        iniciarJUEGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJUEGOActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarJUEGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarJUEGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarJUEGOActionPerformed
        
        JLabel frase1;
        JLabel palabraMostrada;
        JLabel mensaje;
        JLabel contadorOportunidades;
        JTextField campoLetra;
        JButton botonIntentar;
        JButton botonReiniciar;
        JButton botonCambiar;
        JTextArea verPalabras; 
        
        setTitle("JUGAR");
        setSize(600, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        frase1 = new JLabel("Adivina la palabra");
        frase1.setFont(new Font("Arial", Font.BOLD, 18));
        add(frase1);

        palabraMostrada = new JLabel();
        palabraMostrada.setFont(new Font("Arial", Font.PLAIN, 24));
        add(palabraMostrada);

        campoLetra = new JTextField(2);
        campoLetra.setFont(new Font("Arial", Font.PLAIN, 18));
        add(campoLetra);

        botonIntentar = new JButton("Intentar");
        add(botonIntentar);

        contadorOportunidades = new JLabel("Oportunidades: 5");
        add(contadorOportunidades);

        mensaje = new JLabel("");
        mensaje.setPreferredSize(new Dimension(400, 30));
        add(mensaje);

        botonReiniciar = new JButton("Reiniciar");
        botonReiniciar.setEnabled(false);
        add(botonReiniciar);

        botonCambiar = new JButton("Cambiar palabras");
        add(botonCambiar);

        verPalabras = new JTextArea(5, 40);
        verPalabras.setEditable(false);
        add(new JScrollPane(verPalabras));

            }
        

      
        
        
        
        
    }//GEN-LAST:event_iniciarJUEGOActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aguilar_Adrian_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aguilar_Adrian_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aguilar_Adrian_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aguilar_Adrian_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aguilar_Adrian_Main().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarPalabras;
    private javax.swing.JButton iniciarJUEGO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
